from urllib.parse import urlparse


CITY_PROVINCE_MAPPING = {
    "airdrieecho": ("Airdrie", "Alberta"),
    "thecragandcanyon": ("Banff", "Alberta"),
    "thebeaumontnews": ("Beaumont", "Alberta"),
    "calgary": ("Calgary", "Alberta"),
    "cochranetimes": ("Cochrane", "Alberta"),
    "coldlakesun": ("Cold Lake", "Alberta"),
    "devondispatch": ("Edmonton", "Alberta"),
    "draytonvalleywesternreview": ("Edmonton", "Alberta"),
    "edmonton": ("Edmonton", "Alberta"),
    "edmontonjournal": ("Edmonton", "Alberta"),
    "edmontonsun": ("Edmonton", "Alberta"),
    "edson": ("Edson", "Alberta"),
    "fairviewpost": ("Grande Prairie", "Alberta"),
    "fortmcmurraytoday": ("Fort McMurray", "Alberta"),
    "fortsaskatchewanrecord": ("Fort Saskatchewan", "Alberta"),
    "peacecountrysun": ("Grande Prairie", "Alberta"),
    "hannaherald": ("Drumheller", "Alberta"),
    "highrivertimes": ("High River", "Alberta"),
    "hinton": ("Edmonton", "Alberta"),
    "lacombe": ("Lacombe", "Alberta"),
    "leducrep": ("Leduc", "Alberta"),
    "mayerthorpefreelancer": ("Edmonton", "Alberta"),
    "nantonnews": ("Calgary", "Alberta"),
    "prrecordgazette": ("Grande Prairie", "Alberta"),
    "pinchercreekecho": ("Lethbridge", "Alberta"),
    "sherwoodparknews": ("Edmonton", "Alberta"),
    "sprucestony": ("Spruce Grove", "Alberta"),
    "vermilionstandard": ("Lloydminster", "Alberta"),
    "vulcanadvocate": ("Lethbridge", "Alberta"),
    "wetaskiwintimes": ("Wetaskiwin", "Alberta"),
    "whitecourtstar": ("Whitecourt", "Alberta"),
    "princegeorgepost": ("Prince George", "British Columbia"),
    "vancouversunandprovince": ("Vancouver", "British Columbia"),
    "altona": ("Altona", "Manitoba"),
    "beausejour": ("Beausejour", "Manitoba"),
    "carman": ("Carman", "Manitoba"),
    "gimli": ("Winnipeg", "Manitoba"),
    "lacdubonnet": ("Lac du Bonnet", "Manitoba"),
    "morden": ("Morden", "Manitoba"),
    "thegraphicleader": ("Portage la Prairie", "Manitoba"),
    "selkirk": ("Selkirk", "Manitoba"),
    "stonewall": ("Stonewall", "Manitoba"),
    "winkler": ("Winkler", "Manitoba"),
    "winnipegsun": ("Winnipeg", "Manitoba"),
    "northernlight": ("Bathurst", "New Brunswick"),
    "thetribune": ("Campbellton", "New Brunswick"),
    "dailygleaner": ("Fredericton", "New Brunswick"),
    "tjnews": ("Grand Falls & Edmundston", "New Brunswick"),
    "miramichileader": ("Miramichi", "New Brunswick"),
    "timesandtranscript": ("Moncton", "New Brunswick"),
    "letoile": ("Régions Acadiennes", "New Brunswick"),
    "telegraph-journal": ("Saint John", "New Brunswick"),
    "kingscountyrecord": ("Sussex", "New Brunswick"),
    "bugleobserver": ("Woodstock", "New Brunswick"),
    "thetelegram": ("St. John's", "Newfoundland and Labrador"),
    "thenewglasgownews": ("New Glasgow", "Nova Scotia"),
    "intelligencer": ("Belleville", "Ontario"),
    "thechronicleherald": ("Halifax", "Nova Scotia"),
    "brantfordexpositor": ("Brantford", "Ontario"),
    "recorder": ("Brockville", "Ontario"),
    "chathamdailynews": ("Chatham", "Ontario"),
    "clintonnewsrecord": ("Clinton", "Ontario"),
    "cochranetimespost": ("Cochrane", "Ontario"),
    "standard-freeholder": ("Cornwall", "Ontario"),
    "norfolkandtillsonburgnews": ("Delhi", "Ontario"),
    "elliotlakestandard": ("Elliot Lake", "Ontario"),
    "midnorthmonitor": ("Sudbury", "Ontario"),
    "lakeshoreadvance": ("London", "Ontario"),
    "gananoquereporter": ("Kingston", "Ontario"),
    "goderichsignalstar": ("Goderich", "Ontario"),
    "thepost": ("Durham", "Ontario"),
    "kenoraminerandnews": ("Kenora", "Ontario"),
    "kincardinenews": ("Port Elgin", "Ontario"),
    "thewhig": ("Kingston", "Ontario"),
    "northernnews": ("Kirkland Lake", "Ontario"),
    "lfpress": ("London", "Ontario"),
    "lucknowsentinel": ("Lucknow", "Ontario"),
    "mitchelladvocate": ("Mitchell", "Ontario"),
    "napaneeguide": ("Kingston", "Ontario"),
    "nationalpost": ("National Post", "Ontario"),
    "nugget": ("North Bay", "Ontario"),
    "ottawa": ("Ottawa", "Ontario"),
    "owensoundsuntimes": ("Owen Sound", "Ontario"),
    "parisstaronline": ("Brantford", "Ontario"),
    "pembrokeobserver": ("Pembroke", "Ontario"),
    "countyweeklynews": ("Belleville", "Ontario"),
    "shorelinebeacon": ("Port Elgin", "Ontario"),
    "theobserver": ("Sarnia", "Ontario"),
    "saultstar": ("Sault Ste. Marie", "Ontario"),
    "seaforthhuronexpositor": ("Huron County", "Ontario"),
    "simcoereformer": ("Simcoe", "Ontario"),
    "stthomastimesjournal": ("St. Thomas", "Ontario"),
    "communitypress": ("Stirling", "Ontario"),
    "stratfordbeaconherald": ("Stratford", "Ontario"),
    "strathroyagedispatch": ("London", "Ontario"),
    "thesudburystar": ("Sudbury", "Ontario"),
    "timminspress": ("Timmins", "Ontario"),
    "torontosun": ("Toronto", "Ontario"),
    "trentonian": ("Trenton", "Ontario"),
    "wallaceburgcourierpress": ("Wallaceburg", "Ontario"),
    "thechronicle-online": ("St. Thomas", "Ontario"),
    "wiartonecho": ("Wiarton", "Ontario"),
    "windsorstar": ("Windsor", "Ontario"),
    "woodstocksentinelreview": ("Woodstock", "Ontario"),
    "theguardian": ("Charlottetown", "Prince Edward Island"),
    "thejournalpioneer": ("Summerside", "Prince Edward Island"),
    "montrealgazette": ("Montreal", "Quebec"),
    "melfortnipawinjournal": ("Melfort", "Saskatchewan"),
    "leaderpost": ("Regina", "Saskatchewan"),
    "thestarphoenix": ("Saskatoon", "Saskatchewan"),
}


def extract_city_and_province(url):
    parsed_url = urlparse(url)
    if not parsed_url.hostname:
        return None

    subdomain = parsed_url.hostname.split(".")[0]
    return CITY_PROVINCE_MAPPING.get(subdomain.lower())
