"""Add tags column to Obituary and DistinctObituary models

Revision ID: 3c60d2e0a630
Revises: 
Create Date: 2025-03-19 10:59:23.014600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c60d2e0a630'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dist_obituary')
    with op.batch_alter_table('obituary', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('obituary_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('province',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('publication_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('tags',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('obituary', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('publication_date',
               existing_type=sa.String(length=50),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('province',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('obituary_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.create_table('dist_obituary',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('birth_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('death_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('province', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('publication_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('obituary_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('family_information', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('donation_information', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_alumni', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('funeral_home', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dist_obituary_pkey'),
    sa.UniqueConstraint('obituary_url', name='dist_obituary_obituary_url_key')
    )
    # ### end Alembic commands ###
